name: TarkMullAntiXray
version: '${project.version}'
main: ru.tarkmull.antixray.TarkMullAntiXray
api-version: '26.2'
authors: [TarkMull]
description: 'Anti X-Ray: скрытие руд по дистанции + статистический детектор читеров'
folia-supported: false

commands:
  antixray:
    description: Управление античитом X-Ray
    aliases: [axr, ax]
    permission: antixray.admin
    usage: /antixray help

permissions:
  antixray.admin:
    description: Доступ к команде /antixray
    default: op
  antixray.alerts:
    description: Получать оповещения о подозрении на X-Ray
    default: op
  antixray.bypass:
    description: Не скрывать руды и не считать статистику
    default: false
